#!/bin/bash

EXTRA_VOLUMES=$1

# Mount current directory (or specified path) to /workspace in container
# WORKDIR is already set in Dockerfile, we just need to mount the volume
PROJECT_DIR="${2:-$(pwd)}"

docker run --rm \
  -v ollama:/root/.ollama \
  -v "$PROJECT_DIR:/workspace" \
  $EXTRA_VOLUMES \
  -it ollama-docker:latest

